FROM --platform=$TARGETARCH golang:1.22-alpine

ARG TARGETARCH
ARG TARGETOS

WORKDIR /app

COPY go.mod go.sum ./
COPY ./ .

RUN go mod download
RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /app/migrations /app/cmd/migrations

ENTRYPOINT [ "/app/migrations" ]